[package]
name = "sdkwork-api-promotion-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-promotion application HTTP plane."

[lib]
name = "sdkwork_api_promotion_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork_database_sqlx.workspace = true
sdkwork_promotion_service_host.workspace = true
sdkwork_routes_promotion_app_api = { workspace = true }
sdkwork_routes_promotion_backend_api = { workspace = true }
