-- SDKWork promotion consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_promotion_baseline.sql
-- SDKWork promotion consolidated initialization baseline (postgres, commerce schema)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.
--
-- The promotion capability shares the federated commerce database with payment/order/account
-- capabilities. Identifiers, tenants, timestamps, and money amounts are stored as TEXT so the
-- app-side (claim/redeem) and admin-side repositories operate on one canonical schema.
-- Lifecycle statuses are VARCHAR state machines (see STATE_MACHINES in this file's tables).

-- baseline source: ddl/baseline/postgres/0001_promotion_baseline.sql
-- sdkwork:migration
-- id: 0001_promotion_core
-- engine: postgres
-- module: promotion
-- purpose: L2 promotion offer, coupon stock, code, user coupon, ledger, discount application
-- reversible: true
-- transactional: true

CREATE TABLE IF NOT EXISTS promotion_campaign (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    campaign_no VARCHAR(128) NOT NULL,
    campaign_code VARCHAR(128),
    display_name VARCHAR(256) NOT NULL,
    description VARCHAR(1024),
    channel_scope VARCHAR(32) NOT NULL DEFAULT 'ALL',
    audience_scope VARCHAR(32) NOT NULL DEFAULT 'ALL',
    starts_at TEXT NOT NULL,
    ends_at TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    version BIGINT NOT NULL DEFAULT 0,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_campaign_no UNIQUE (tenant_id, campaign_no)
);

CREATE INDEX IF NOT EXISTS idx_promotion_campaign_tenant_status
    ON promotion_campaign (tenant_id, organization_id, status, starts_at DESC);

CREATE TABLE IF NOT EXISTS promotion_offer (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    campaign_id TEXT,
    offer_no VARCHAR(128) NOT NULL,
    offer_code VARCHAR(128),
    offer_type VARCHAR(32) NOT NULL,
    audience_scope VARCHAR(32) NOT NULL DEFAULT 'ALL',
    combinability VARCHAR(32) NOT NULL DEFAULT 'EXCLUSIVE',
    priority INTEGER NOT NULL DEFAULT 0,
    goods_scope VARCHAR(32) NOT NULL DEFAULT 'BOTH',
    current_offer_version_id TEXT,
    display_name VARCHAR(256) NOT NULL,
    description VARCHAR(1024),
    starts_at TEXT NOT NULL,
    ends_at TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_offer_no UNIQUE (tenant_id, offer_no)
);

CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_status
    ON promotion_offer (tenant_id, organization_id, status, priority DESC, starts_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_type
    ON promotion_offer (tenant_id, offer_type, status);
CREATE INDEX IF NOT EXISTS idx_promotion_offer_campaign
    ON promotion_offer (tenant_id, organization_id, campaign_id, status);

CREATE TABLE IF NOT EXISTS promotion_offer_version (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    offer_id TEXT NOT NULL,
    version_no INTEGER NOT NULL,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'published',
    discount_type VARCHAR(32) NOT NULL,
    discount_value TEXT NOT NULL DEFAULT '0',
    minimum_amount TEXT NOT NULL DEFAULT '0',
    maximum_discount_amount TEXT,
    maximum_quantity_per_order INTEGER NOT NULL DEFAULT 1,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    rule_json TEXT,
    stack_rule_json TEXT,
    published_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_offer_version_unique UNIQUE (tenant_id, offer_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_promotion_offer_version_offer
    ON promotion_offer_version (tenant_id, offer_id, version_no DESC);

CREATE TABLE IF NOT EXISTS promotion_coupon_stock (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    stock_no VARCHAR(128) NOT NULL,
    stock_type VARCHAR(32) NOT NULL,
    code_issue_mode VARCHAR(16) NOT NULL DEFAULT 'REALTIME',
    total_quantity BIGINT NOT NULL DEFAULT 0,
    available_quantity BIGINT NOT NULL DEFAULT 0,
    claimed_quantity BIGINT NOT NULL DEFAULT 0,
    redeemed_quantity BIGINT NOT NULL DEFAULT 0,
    locked_quantity BIGINT NOT NULL DEFAULT 0,
    per_user_limit INTEGER NOT NULL DEFAULT 1,
    claim_starts_at TEXT,
    claim_ends_at TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_coupon_stock_no UNIQUE (tenant_id, stock_no),
    CONSTRAINT chk_promotion_coupon_stock_quantities_non_negative CHECK (
        total_quantity >= 0 AND available_quantity >= 0 AND claimed_quantity >= 0
        AND redeemed_quantity >= 0 AND locked_quantity >= 0
    ),
    CONSTRAINT chk_promotion_coupon_stock_available_le_total CHECK (
        stock_type = 'UNLIMITED' OR (available_quantity + claimed_quantity <= total_quantity)
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_coupon_stock_offer
    ON promotion_coupon_stock (tenant_id, offer_id, status);

CREATE TABLE IF NOT EXISTS promotion_code_batch (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    stock_id TEXT NOT NULL,
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    batch_no VARCHAR(128) NOT NULL,
    code_type VARCHAR(32) NOT NULL,
    requested_quantity BIGINT NOT NULL,
    generated_quantity BIGINT NOT NULL DEFAULT 0,
    code_length INTEGER NOT NULL DEFAULT 16,
    code_prefix VARCHAR(32) NOT NULL DEFAULT '',
    starts_at TEXT,
    expires_at TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    idempotency_key VARCHAR(200) NOT NULL,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_code_batch_no UNIQUE (tenant_id, batch_no),
    CONSTRAINT uk_promotion_code_batch_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT chk_promotion_code_batch_quantity CHECK (requested_quantity > 0 AND generated_quantity >= 0 AND generated_quantity <= requested_quantity),
    CONSTRAINT chk_promotion_code_batch_length CHECK (code_length BETWEEN 12 AND 32)
);

CREATE INDEX IF NOT EXISTS idx_promotion_code_batch_stock
    ON promotion_code_batch (tenant_id, organization_id, stock_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS promotion_code (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    code_batch_id TEXT,
    stock_id TEXT NOT NULL,
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    code_no VARCHAR(128) NOT NULL,
    promotion_code VARCHAR(128) NOT NULL,
    code_type VARCHAR(32) NOT NULL,
    max_claims INTEGER NOT NULL DEFAULT 1,
    claimed_quantity INTEGER NOT NULL DEFAULT 0,
    starts_at TEXT,
    expires_at TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_code_no UNIQUE (tenant_id, code_no),
    CONSTRAINT uk_promotion_code_value UNIQUE (tenant_id, promotion_code),
    CONSTRAINT chk_promotion_code_claimed_le_max CHECK (claimed_quantity <= max_claims)
);

CREATE INDEX IF NOT EXISTS idx_promotion_code_stock
    ON promotion_code (tenant_id, stock_id, status);
CREATE INDEX IF NOT EXISTS idx_promotion_code_batch
    ON promotion_code (tenant_id, code_batch_id, status);

CREATE TABLE IF NOT EXISTS promotion_user_coupon (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    coupon_no VARCHAR(128) NOT NULL,
    stock_id TEXT NOT NULL,
    code_id TEXT,
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    coupon_code VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'claimed',
    claimed_at TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    expires_at TEXT,
    redeemed_at TEXT,
    disabled_at TEXT,
    source_type VARCHAR(64),
    source_id TEXT,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_user_coupon_no UNIQUE (tenant_id, coupon_no),
    CONSTRAINT uk_promotion_user_coupon_code UNIQUE (tenant_id, coupon_code),
    CONSTRAINT uk_promotion_user_coupon_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_user_coupon_owner_status_expires
    ON promotion_user_coupon (tenant_id, owner_user_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_promotion_user_coupon_offer
    ON promotion_user_coupon (tenant_id, offer_id, status);

CREATE TABLE IF NOT EXISTS promotion_distribution_task (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    stock_id TEXT NOT NULL,
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    task_no VARCHAR(128) NOT NULL,
    distribution_type VARCHAR(32) NOT NULL DEFAULT 'DIRECT',
    requested_quantity BIGINT NOT NULL,
    succeeded_quantity BIGINT NOT NULL DEFAULT 0,
    failed_quantity BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    idempotency_key VARCHAR(200) NOT NULL,
    created_by TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_distribution_task_no UNIQUE (tenant_id, task_no),
    CONSTRAINT uk_promotion_distribution_task_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT chk_promotion_distribution_task_quantities CHECK (requested_quantity > 0 AND succeeded_quantity >= 0 AND failed_quantity >= 0 AND succeeded_quantity + failed_quantity <= requested_quantity)
);

CREATE INDEX IF NOT EXISTS idx_promotion_distribution_task_stock
    ON promotion_distribution_task (tenant_id, organization_id, stock_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS promotion_distribution_record (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    task_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    user_coupon_id TEXT,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(64),
    failure_detail VARCHAR(512),
    created_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_distribution_record_target UNIQUE (tenant_id, task_id, owner_user_id)
);

CREATE INDEX IF NOT EXISTS idx_promotion_distribution_record_task
    ON promotion_distribution_record (tenant_id, task_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_distribution_record_owner
    ON promotion_distribution_record (tenant_id, owner_user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS promotion_coupon_ledger_entry (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    stock_id TEXT NOT NULL,
    user_coupon_id TEXT,
    offer_id TEXT NOT NULL,
    subject_type VARCHAR(32),
    subject_id TEXT,
    direction VARCHAR(16) NOT NULL,
    quantity_delta BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_no VARCHAR(128) NOT NULL,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    source_type VARCHAR(64),
    source_id TEXT,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_coupon_ledger_entry_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_coupon_ledger_entry_stock_created
    ON promotion_coupon_ledger_entry (tenant_id, stock_id, created_at DESC);

CREATE TABLE IF NOT EXISTS promotion_discount_application (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    application_no VARCHAR(128) NOT NULL,
    order_id TEXT NOT NULL,
    order_no VARCHAR(128),
    user_coupon_id TEXT,
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    discount_type VARCHAR(32) NOT NULL,
    discount_amount TEXT NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    discount_details_json TEXT,
    goods_type VARCHAR(32) NOT NULL DEFAULT 'BOTH',
    status VARCHAR(32) NOT NULL DEFAULT 'applied',
    applied_at TEXT NOT NULL,
    settled_at TEXT,
    released_at TEXT,
    rolled_back_at TEXT,
    release_reason VARCHAR(512),
    rollback_reason VARCHAR(512),
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_discount_application_no UNIQUE (tenant_id, application_no),
    CONSTRAINT uk_promotion_discount_application_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_discount_application_owner_status
    ON promotion_discount_application (tenant_id, owner_user_id, status, applied_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_discount_application_order
    ON promotion_discount_application (tenant_id, order_id, status);

-- folded migration: migrations/postgres/0002_marketing_admin.up.sql
-- sdkwork:migration
-- id: 0002_marketing_admin
-- engine: postgres
-- module: promotion
-- purpose: campaign, code batch, and direct coupon distribution administration
-- reversible: false
-- transactional: true

ALTER TABLE promotion_offer ADD COLUMN IF NOT EXISTS campaign_id TEXT;
ALTER TABLE promotion_code ADD COLUMN IF NOT EXISTS code_batch_id TEXT;









CREATE INDEX IF NOT EXISTS idx_promotion_campaign_tenant_status ON promotion_campaign (tenant_id, organization_id, status, starts_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_offer_campaign ON promotion_offer (tenant_id, organization_id, campaign_id, status);
CREATE INDEX IF NOT EXISTS idx_promotion_code_batch_stock ON promotion_code_batch (tenant_id, organization_id, stock_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_code_batch ON promotion_code (tenant_id, code_batch_id, status);
CREATE INDEX IF NOT EXISTS idx_promotion_distribution_task_stock ON promotion_distribution_task (tenant_id, organization_id, stock_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_distribution_record_task ON promotion_distribution_record (tenant_id, task_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_distribution_record_owner ON promotion_distribution_record (tenant_id, owner_user_id, created_at DESC);

-- folded migration: migrations/postgres/0003_coupon_code_issue_mode.up.sql
-- sdkwork:migration
-- id: 0003_coupon_code_issue_mode
-- engine: postgres
-- module: promotion
-- purpose: mark coupon stock code issuance mode (realtime claim code vs pre-generated batch pool)
-- reversible: false
-- transactional: true

ALTER TABLE promotion_coupon_stock ADD COLUMN IF NOT EXISTS code_issue_mode VARCHAR(16) NOT NULL DEFAULT 'REALTIME';

-- folded migration: migrations/postgres/0004_member_card.up.sql
-- sdkwork:migration
-- id: 0004_member_card
-- engine: postgres
-- module: promotion
-- purpose: independent member card system for subscription coupon benefits (card head + quota consumption ledger)
-- reversible: false
-- transactional: true

CREATE TABLE IF NOT EXISTS promotion_member_card (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    card_no VARCHAR(128) NOT NULL,
    offer_id TEXT NOT NULL,
    offer_version_id TEXT NOT NULL,
    user_coupon_id TEXT NOT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    period VARCHAR(16) NOT NULL,
    duration_days BIGINT NOT NULL,
    daily_quota BIGINT NOT NULL,
    total_quota BIGINT NOT NULL,
    total_used BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    starts_at TEXT NOT NULL,
    expires_at TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_member_card_no UNIQUE (tenant_id, card_no),
    CONSTRAINT uk_promotion_member_card_coupon UNIQUE (tenant_id, user_coupon_id),
    CONSTRAINT chk_promotion_member_card_quota CHECK (daily_quota > 0 AND total_quota >= daily_quota AND total_used >= 0 AND total_used <= total_quota)
);

CREATE TABLE IF NOT EXISTS promotion_member_card_consumption (
    id TEXT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    card_id TEXT NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    source_type VARCHAR(64),
    source_id TEXT,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    CONSTRAINT uk_promotion_member_card_consumption_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT chk_promotion_member_card_consumption_amount CHECK (amount > 0 AND balance_after >= 0)
);

CREATE INDEX IF NOT EXISTS idx_promotion_member_card_owner ON promotion_member_card (tenant_id, organization_id, owner_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_member_card_consumption_card ON promotion_member_card_consumption (tenant_id, card_id, occurred_at DESC);

-- folded migration: migrations/postgres/0005_enum_normalization_and_benefit_columns.up.sql
-- sdkwork:migration
-- id: 0005_enum_normalization_and_benefit_columns
-- engine: postgres
-- module: promotion
-- purpose: normalize status/type enums to lowercase, materialize coupon benefit columns for SQL querying, add offer soft-delete column
-- reversible: false
-- transactional: true

-- ============ 1. 状态/类型枚举统一小写 ============

-- promotion_campaign.status
UPDATE promotion_campaign SET status = LOWER(status);
ALTER TABLE promotion_campaign ALTER COLUMN status SET DEFAULT 'draft';

-- promotion_code_batch.status
UPDATE promotion_code_batch SET status = LOWER(status);
ALTER TABLE promotion_code_batch ALTER COLUMN status SET DEFAULT 'pending';

-- promotion_distribution_task.status
UPDATE promotion_distribution_task SET status = LOWER(status);
ALTER TABLE promotion_distribution_task ALTER COLUMN status SET DEFAULT 'pending';

-- promotion_coupon_stock.stock_type
UPDATE promotion_coupon_stock SET stock_type = LOWER(stock_type);
ALTER TABLE promotion_coupon_stock DROP CONSTRAINT IF EXISTS chk_promotion_coupon_stock_type;
ALTER TABLE promotion_coupon_stock ADD CONSTRAINT chk_promotion_coupon_stock_type CHECK (stock_type IN ('limited', 'unlimited'));

-- promotion_coupon_stock.code_issue_mode
UPDATE promotion_coupon_stock SET code_issue_mode = LOWER(code_issue_mode);
ALTER TABLE promotion_coupon_stock ALTER COLUMN code_issue_mode SET DEFAULT 'realtime';

-- 历史核销/回滚状态对齐契约枚举
UPDATE promotion_user_coupon SET status = 'redeemed' WHERE status = 'used';
UPDATE promotion_discount_application SET status = 'rolled_back' WHERE status = 'reversed';

-- ============ 2. 权益结构化列（promotion_offer_version） ============

ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_kind VARCHAR(32);
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_grant_amount TEXT;
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_bonus_amount TEXT;
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_grant_points TEXT;
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_period VARCHAR(16);
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_duration_days BIGINT;
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_daily_quota BIGINT;
ALTER TABLE promotion_offer_version ADD COLUMN IF NOT EXISTS benefit_total_quota BIGINT;

-- 存量回填：从 rule_json 提取权益写入结构化列（rule_json 结构 {"couponBenefit":{...}}）
UPDATE promotion_offer_version
SET benefit_kind = LOWER(COALESCE(rule_json::jsonb #>> '{couponBenefit,kind}', rule_json::jsonb #>> '{benefit,kind}')),
    benefit_grant_amount = COALESCE(rule_json::jsonb #>> '{couponBenefit,grantAmount}', rule_json::jsonb #>> '{benefit,grantAmount}'),
    benefit_bonus_amount = COALESCE(rule_json::jsonb #>> '{couponBenefit,bonusAmount}', rule_json::jsonb #>> '{benefit,bonusAmount}'),
    benefit_grant_points = COALESCE(rule_json::jsonb #>> '{couponBenefit,grantPoints}', rule_json::jsonb #>> '{benefit,grantPoints}'),
    benefit_period = COALESCE(rule_json::jsonb #>> '{couponBenefit,period}', rule_json::jsonb #>> '{benefit,period}'),
    benefit_duration_days = COALESCE(
        (rule_json::jsonb #>> '{couponBenefit,durationDays}')::BIGINT,
        (rule_json::jsonb #>> '{benefit,durationDays}')::BIGINT
    ),
    benefit_daily_quota = COALESCE(
        (rule_json::jsonb #>> '{couponBenefit,dailyQuota}')::BIGINT,
        (rule_json::jsonb #>> '{benefit,dailyQuota}')::BIGINT
    ),
    benefit_total_quota = COALESCE(
        (rule_json::jsonb #>> '{couponBenefit,totalQuota}')::BIGINT,
        (rule_json::jsonb #>> '{benefit,totalQuota}')::BIGINT
    )
WHERE rule_json IS NOT NULL AND rule_json <> '';

-- ============ 3. Offer 软删除列 ============

ALTER TABLE promotion_offer ADD COLUMN IF NOT EXISTS deleted_at TEXT;
CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_status_deleted
    ON promotion_offer (tenant_id, organization_id, status, deleted_at, priority DESC, starts_at DESC);
